name: BrowserStack App Automate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Run test on BrowserStack
        run: |
          cat > browserstack_test.js <<EOL
          const webdriver = require('selenium-webdriver');
          const capabilities = {
            'browserstack.user': '${{ secrets.BROWSERSTACK_USERNAME }}',
            'browserstack.key': '${{ secrets.BROWSERSTACK_ACCESS_KEY }}',
            'app': 'https://endtest-drive.s3.us-west-2.amazonaws.com/T9IokbL55J5DcoNMHS6MDjGUPukWZ4/Business_and_Finance_%284%29.apk',
            'device': 'Google Pixel 5',
            'os_version': '11.0',
            'project': 'Business Finance App Test',
            'build': 'GitHub Actions Build ${{ github.run_number }}',
            'name': 'simple_test'
          };
          
          async function runTest() {
            let driver = new webdriver.Builder()
              .usingServer('https://hub-cloud.browserstack.com/wd/hub')
              .withCapabilities(capabilities)
              .build();
              
            try {
              // Add your test commands here
              await driver.sleep(5000);
              console.log('Test completed successfully');
            } finally {
              await driver.quit();
            }
          }
          
          runTest();
          EOL
          
          npm install selenium-webdriver
          node browserstack_test.js
